
// src/app/cookie-policy/page.tsx
import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Cookie Policy - WorldAIPedia',
  description: 'Cookie Policy for WorldAIPedia, your guide to Artificial Intelligence.',
};

export default function CookiePolicyPage() {
  const lastUpdatedDate = "July 26, 2024"; // Update this date whenever the policy changes
  const contactEmail = "lacelabswebs@gmail.com"; // Updated contact email

  return (
    <div className="container mx-auto py-8 px-4 max-w-3xl">
      <h1 className="text-3xl font-headline font-bold text-primary mb-6">Cookie Policy for WorldAIPedia</h1>
      <p className="text-sm text-muted-foreground mb-6">Last Updated: {lastUpdatedDate}</p>

      <section className="space-y-4 mb-8">
        <h2 className="text-2xl font-headline font-semibold text-primary/90 mb-3">1. What are Cookies?</h2>
        <p>Cookies are small text files that are stored on your computer or mobile device when you visit a website. They allow the website to remember your actions and preferences (such as login, language, font size, and other display preferences) over a period of time, so you don’t have to keep re-entering them whenever you come back to the site or browse from one page to another.</p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-2xl font-headline font-semibold text-primary/90 mb-3">2. How We Use Cookies</h2>
        <p>WorldAIPedia uses cookies for the following purposes:</p>
        <ul className="list-disc list-inside space-y-1 pl-4 text-foreground/80">
          <li>
            <strong>Functional Cookies:</strong> These cookies are essential for the website to function properly. They enable basic functionalities like page navigation, access to secure areas (if applicable, e.g., for logged-in users managing their PRO subscription), and remembering your cookie consent preferences.
          </li>
          <li>
            <strong>Analytical Cookies:</strong> We use these cookies to understand how visitors interact with our website. We use Google Analytics, a web analytics service provided by Google, Inc. Google Analytics uses cookies to help us analyze how users use the site, such as which pages are visited most often and if users get error messages from web pages. This information is used to improve the website's performance and user experience. The information generated by the cookie about your use of the website will be transmitted to and stored by Google.
          </li>
        </ul>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-2xl font-headline font-semibold text-primary/90 mb-3">3. Your Consent</h2>
        <p>By continuing to browse and use WorldAIPedia, you are agreeing to our use of cookies as described in this policy. If you do not agree to the use of cookies, you should adjust your browser settings accordingly or refrain from using the Site.</p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-2xl font-headline font-semibold text-primary/90 mb-3">4. Managing Cookies</h2>
        <p>Most web browsers allow you to control cookies through their settings preferences. You can set your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, some parts of our Site may not function properly.</p>
        <p>For more information on how to manage cookies, you can refer to your browser's help documentation or visit websites like <a href="https://www.aboutcookies.org" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">www.aboutcookies.org</a>.</p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-headline font-semibold text-primary/90 mb-3">5. Changes to This Cookie Policy</h2>
        <p>We may update this Cookie Policy from time to time. We will notify you of any changes by posting the new Cookie Policy on this page and updating the "Last Updated" date.</p>
      </section>
      
      <section className="space-y-4 mt-8">
        <h2 className="text-2xl font-headline font-semibold text-primary/90 mb-3">6. Contact Us</h2>
        <p>If you have any questions about this Cookie Policy, please contact us at: <a href={`mailto:${contactEmail}`} className="text-primary hover:underline">{contactEmail}</a></p>
      </section>
    </div>
  );
}
